### PR TITLE
Validate `dtype`-s in `where` to avoid exception

### PR DESCRIPTION
**Pull request by MatejUrbanQC**
This enables custom type overrides to operate with one argument being a core type.

### CODE REVIEW

**Review by adityagoel4512 — APPROVED** [review]
This is ready to go to me @MatejUrbanQC. Any final thoughts/concerns?

**Comment by neNasko1** [comment]
LGTM as well.

**Review by neNasko1 — APPROVED** [review]

**Comment by MatejUrbanQC** [comment]
I don't like that there is an implicit dependency of `CoreOperationsImpl` on `UniformShapeOperations` in the `where` operation. It would be explicit if `CoreOperationsImpl` would inherit from `UniformShapeOperations` (we would need to change the inheritance structure slightly)

**Comment by adityagoel4512** [comment]
> We could make it explicit by CoreOperationsImpl inheriting from UniformShapeOperations (we would need to change the inheritance structure slightly)

https://github.com/Quantco/ndonnx/pull/70/commits/434d3903c9f59f08435017619c4c266654812bb8 does precisely this?

**Comment by adityagoel4512** [comment]
> I don't like that there is an implicit dependency of `CoreOperationsImpl` on `UniformShapeOperations` in the `where` operation.
> 
> We could make it explicit by `CoreOperationsImpl` inheriting from `UniformShapeOperations` (we would need to change the inheritance structure slightly)

Totally, good catch.

**Comment by adityagoel4512** [comment]
> I don't like that there is an implicit dependency of `CoreOperationsImpl` on `UniformShapeOperations` in the `where` operation.
> 
> We could make it explicit by `CoreOperationsImpl` inheriting from `UniformShapeOperations` (we would need to change the inheritance structure slightly)

Totally, I don't think https://github.com/Quantco/ndonnx/pull/70/commits/434d3903c9f59f08435017619c4c266654812bb8 did quite what it set out to 😀.

**Pull request merged**
